import { Viewport, Table, Meter, ScrollView, Block, Button } from '@flow-ui/core'
import React from 'react'
import ReactDOM from 'react-dom'
// import App from './app'
import custom from './themes/custom'

const Playground = () => {
	return (
		<Viewport theme={custom}>
			{/* <App /> */}
			<ScrollView mode="scroll">
				<Table
					experimental={{
						renderType: 'mountUnmount',
						tableRowHeight: (index) => 100
					}}
					columns={[
						{
							title: 'Fullname', key: 'name', render: (e) => {
								return (
									<Block>
										<Button>{e.row['name']}</Button>
									</Block>
								)
							}
						},
						{
							title: 'Age', key: 'age', width: 20, render: (e) => {
								return (
									<Meter w="200px" value={e.row['age']} />
								)
							}
						},
					]}
					data={[
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },
						{ name: 'Matt', age: 25 },
						{ name: 'John', age: 29 },
						{ name: 'Kate', age: 26 },

					]}
				/>
			</ScrollView>
		</Viewport>
	)
}

ReactDOM.render(
	<Playground />,
	document.getElementById('app')
)