declare namespace IconsetTypes {

    type Filled = {
        activity: React.ReactElement
        alertCircle: React.ReactElement
        alertTriangle: React.ReactElement
        archive: React.ReactElement
        arrowBack: React.ReactElement
        arrowCircleDown: React.ReactElement
        arrowCircleLeft: React.ReactElement
        arrowCircleRight: React.ReactElement
        arrowCircleUp: React.ReactElement
        arrowDown: React.ReactElement
        arrowDownward: React.ReactElement
        arrowForward: React.ReactElement
        arrowIosBack: React.ReactElement
        arrowIosDownward: React.ReactElement
        arrowIosForward: React.ReactElement
        arrowIosUpward: React.ReactElement
        arrowLeft: React.ReactElement
        arrowRight: React.ReactElement
        arrowUp: React.ReactElement
        arrowUpward: React.ReactElement
        arrowheadDown: React.ReactElement
        arrowheadLeft: React.ReactElement
        arrowheadRight: React.ReactElement
        arrowheadUp: React.ReactElement
        at: React.ReactElement
        attach2: React.ReactElement
        attach: React.ReactElement
        award: React.ReactElement
        backspace: React.ReactElement
        barChart2: React.ReactElement
        barChart: React.ReactElement
        battery: React.ReactElement
        behance: React.ReactElement
        bellOff: React.ReactElement
        bell: React.ReactElement
        bluetooth: React.ReactElement
        bookOpen: React.ReactElement
        book: React.ReactElement
        bookmark: React.ReactElement
        briefcase: React.ReactElement
        browser: React.ReactElement
        brush: React.ReactElement
        bulb: React.ReactElement
        calendar: React.ReactElement
        camera: React.ReactElement
        car: React.ReactElement
        cast: React.ReactElement
        charging: React.ReactElement
        checkmarkCircle2: React.ReactElement
        checkmarkCircle: React.ReactElement
        checkmarkSquare2: React.ReactElement
        checkmarkSquare: React.ReactElement
        checkmark: React.ReactElement
        chevronDown: React.ReactElement
        chevronLeft: React.ReactElement
        chevronRight: React.ReactElement
        chevronUp: React.ReactElement
        clipboard: React.ReactElement
        clock: React.ReactElement
        closeCircle: React.ReactElement
        closeSquare: React.ReactElement
        close: React.ReactElement
        cloudDownload: React.ReactElement
        cloudUpload: React.ReactElement
        codeDownload: React.ReactElement
        code: React.ReactElement
        collapse: React.ReactElement
        colorPalette: React.ReactElement
        colorPicker: React.ReactElement
        compass: React.ReactElement
        copy: React.ReactElement
        cornerDownLeft: React.ReactElement
        cornerDownRight: React.ReactElement
        cornerLeftDown: React.ReactElement
        cornerLeftUp: React.ReactElement
        cornerRightDown: React.ReactElement
        cornerRightUp: React.ReactElement
        cornerUpLeft: React.ReactElement
        cornerUpRight: React.ReactElement
        creditCard: React.ReactElement
        crop: React.ReactElement
        cube: React.ReactElement
        diagonalArrowLeftDown: React.ReactElement
        diagonalArrowLeftUp: React.ReactElement
        diagonalArrowRightDown: React.ReactElement
        diagonalArrowRightUp: React.ReactElement
        doneAll: React.ReactElement
        download: React.ReactElement
        dropletOff: React.ReactElement
        droplet: React.ReactElement
        edit2: React.ReactElement
        edit: React.ReactElement
        email: React.ReactElement
        expand: React.ReactElement
        externalLink: React.ReactElement
        eyeOff2: React.ReactElement
        eyeOff: React.ReactElement
        eye: React.ReactElement
        facebook: React.ReactElement
        fileAdd: React.ReactElement
        fileRemove: React.ReactElement
        fileText: React.ReactElement
        file: React.ReactElement
        film: React.ReactElement
        flag: React.ReactElement
        flashOff: React.ReactElement
        flash: React.ReactElement
        flip2: React.ReactElement
        flip: React.ReactElement
        folderAdd: React.ReactElement
        folderRemove: React.ReactElement
        folder: React.ReactElement
        funnel: React.ReactElement
        gift: React.ReactElement
        github: React.ReactElement
        globe2: React.ReactElement
        globe3: React.ReactElement
        globe: React.ReactElement
        google: React.ReactElement
        grid: React.ReactElement
        hardDrive: React.ReactElement
        hash: React.ReactElement
        headphones: React.ReactElement
        heart: React.ReactElement
        home: React.ReactElement
        image2: React.ReactElement
        image: React.ReactElement
        inbox: React.ReactElement
        info: React.ReactElement
        keypad: React.ReactElement
        layers: React.ReactElement
        layout: React.ReactElement
        link2: React.ReactElement
        link: React.ReactElement
        linkedin: React.ReactElement
        list: React.ReactElement
        lock: React.ReactElement
        logIn: React.ReactElement
        logOut: React.ReactElement
        map: React.ReactElement
        maximize: React.ReactElement
        menu2: React.ReactElement
        menuArrow: React.ReactElement
        menu: React.ReactElement
        messageCircle: React.ReactElement
        messageSquare: React.ReactElement
        micOff: React.ReactElement
        mic: React.ReactElement
        minimize: React.ReactElement
        minusCircle: React.ReactElement
        minusSquare: React.ReactElement
        minus: React.ReactElement
        monitor: React.ReactElement
        moon: React.ReactElement
        moreHorizontal: React.ReactElement
        moreVertical: React.ReactElement
        move: React.ReactElement
        music: React.ReactElement
        navigation2: React.ReactElement
        navigation: React.ReactElement
        npm: React.ReactElement
        options2: React.ReactElement
        options: React.ReactElement
        pantone: React.ReactElement
        paperPlane: React.ReactElement
        pauseCircle: React.ReactElement
        people: React.ReactElement
        percent: React.ReactElement
        personAdd: React.ReactElement
        personDelete: React.ReactElement
        personDone: React.ReactElement
        personRemove: React.ReactElement
        person: React.ReactElement
        phoneCall: React.ReactElement
        phoneMissed: React.ReactElement
        phoneOff: React.ReactElement
        phone: React.ReactElement
        pieChart2: React.ReactElement
        pieChart: React.ReactElement
        pin: React.ReactElement
        playCircle: React.ReactElement
        plusCircle: React.ReactElement
        plusSquare: React.ReactElement
        plus: React.ReactElement
        power: React.ReactElement
        pricetags: React.ReactElement
        printer: React.ReactElement
        questionMarkCircle: React.ReactElement
        questionMark: React.ReactElement
        radioButtonOff: React.ReactElement
        radioButtonOn: React.ReactElement
        radio: React.ReactElement
        recording: React.ReactElement
        refresh: React.ReactElement
        repeat: React.ReactElement
        rewindLeft: React.ReactElement
        rewindRight: React.ReactElement
        save: React.ReactElement
        scissors: React.ReactElement
        search: React.ReactElement
        settings2: React.ReactElement
        settings: React.ReactElement
        shake: React.ReactElement
        share: React.ReactElement
        shieldOff: React.ReactElement
        shield: React.ReactElement
        shoppingBag: React.ReactElement
        shoppingCart: React.ReactElement
        shuffle2: React.ReactElement
        shuffle: React.ReactElement
        skipBack: React.ReactElement
        skipForward: React.ReactElement
        slash: React.ReactElement
        smartphone: React.ReactElement
        speaker: React.ReactElement
        square: React.ReactElement
        star: React.ReactElement
        stopCircle: React.ReactElement
        sun: React.ReactElement
        swap: React.ReactElement
        sync: React.ReactElement
        text: React.ReactElement
        thermometerMinus: React.ReactElement
        thermometerPlus: React.ReactElement
        thermometer: React.ReactElement
        toggleLeft: React.ReactElement
        toggleRight: React.ReactElement
        trash2: React.ReactElement
        trash: React.ReactElement
        trendingDown: React.ReactElement
        trendingUp: React.ReactElement
        tv: React.ReactElement
        twitter: React.ReactElement
        umbrella: React.ReactElement
        undo: React.ReactElement
        unlock: React.ReactElement
        upload: React.ReactElement
        videoOff: React.ReactElement
        video: React.ReactElement
        volumeDown: React.ReactElement
        volumeMute: React.ReactElement
        volumeOff: React.ReactElement
        volumeUp: React.ReactElement
        wifiOff: React.ReactElement
        wifi: React.ReactElement
    }

    type Outline = {
        activity: React.ReactElement
        alertCircle: React.ReactElement
        alertTriangle: React.ReactElement
        archive: React.ReactElement
        arrowBack: React.ReactElement
        arrowCircleDown: React.ReactElement
        arrowCircleLeft: React.ReactElement
        arrowCircleRight: React.ReactElement
        arrowCircleUp: React.ReactElement
        arrowDown: React.ReactElement
        arrowDownward: React.ReactElement
        arrowForward: React.ReactElement
        arrowIosBack: React.ReactElement
        arrowIosDownward: React.ReactElement
        arrowIosForward: React.ReactElement
        arrowIosUpward: React.ReactElement
        arrowLeft: React.ReactElement
        arrowRight: React.ReactElement
        arrowUp: React.ReactElement
        arrowUpward: React.ReactElement
        arrowheadDown: React.ReactElement
        arrowheadLeft: React.ReactElement
        arrowheadRight: React.ReactElement
        arrowheadUp: React.ReactElement
        at: React.ReactElement
        attach2: React.ReactElement
        attach: React.ReactElement
        award: React.ReactElement
        backspace: React.ReactElement
        barChart2: React.ReactElement
        barChart: React.ReactElement
        battery: React.ReactElement
        behance: React.ReactElement
        bellOff: React.ReactElement
        bell: React.ReactElement
        bluetooth: React.ReactElement
        bookOpen: React.ReactElement
        book: React.ReactElement
        bookmark: React.ReactElement
        briefcase: React.ReactElement
        browser: React.ReactElement
        brush: React.ReactElement
        bulb: React.ReactElement
        calendar: React.ReactElement
        camera: React.ReactElement
        car: React.ReactElement
        cast: React.ReactElement
        charging: React.ReactElement
        checkmarkCircle2: React.ReactElement
        checkmarkCircle: React.ReactElement
        checkmark: React.ReactElement
        checkmarkSquare2: React.ReactElement
        checkmarkSquare: React.ReactElement
        chevronDown: React.ReactElement
        chevronLeft: React.ReactElement
        chevronRight: React.ReactElement
        chevronUp: React.ReactElement
        clipboard: React.ReactElement
        clock: React.ReactElement
        closeCircle: React.ReactElement
        close: React.ReactElement
        closeSquare: React.ReactElement
        cloudDownload: React.ReactElement
        cloudUpload: React.ReactElement
        codeDownload: React.ReactElement
        code: React.ReactElement
        collapse: React.ReactElement
        colorPalette: React.ReactElement
        colorPicker: React.ReactElement
        compass: React.ReactElement
        copy: React.ReactElement
        cornerDownLeft: React.ReactElement
        cornerDownRight: React.ReactElement
        cornerLeftDown: React.ReactElement
        cornerLeftUp: React.ReactElement
        cornerRightDown: React.ReactElement
        cornerRightUp: React.ReactElement
        cornerUpLeft: React.ReactElement
        cornerUpRight: React.ReactElement
        creditCard: React.ReactElement
        crop: React.ReactElement
        cube: React.ReactElement
        diagonalArrowLeftDown: React.ReactElement
        diagonalArrowLeftUp: React.ReactElement
        diagonalArrowRightDown: React.ReactElement
        diagonalArrowRightUp: React.ReactElement
        doneAll: React.ReactElement
        download: React.ReactElement
        dropletOff: React.ReactElement
        droplet: React.ReactElement
        edit2: React.ReactElement
        edit: React.ReactElement
        email: React.ReactElement
        expand: React.ReactElement
        externalLink: React.ReactElement
        eyeOff2: React.ReactElement
        eyeOff: React.ReactElement
        eye: React.ReactElement
        facebook: React.ReactElement
        fileAdd: React.ReactElement
        file: React.ReactElement
        fileRemove: React.ReactElement
        fileText: React.ReactElement
        film: React.ReactElement
        flag: React.ReactElement
        flashOff: React.ReactElement
        flash: React.ReactElement
        flip2: React.ReactElement
        flip: React.ReactElement
        folderAdd: React.ReactElement
        folder: React.ReactElement
        folderRemove: React.ReactElement
        funnel: React.ReactElement
        gift: React.ReactElement
        github: React.ReactElement
        globe2: React.ReactElement
        globe: React.ReactElement
        google: React.ReactElement
        grid: React.ReactElement
        hardDrive: React.ReactElement
        hash: React.ReactElement
        headphones: React.ReactElement
        heart: React.ReactElement
        home: React.ReactElement
        image: React.ReactElement
        inbox: React.ReactElement
        info: React.ReactElement
        keypad: React.ReactElement
        layers: React.ReactElement
        layout: React.ReactElement
        link2: React.ReactElement
        link: React.ReactElement
        linkedin: React.ReactElement
        list: React.ReactElement
        loader: React.ReactElement
        lock: React.ReactElement
        logIn: React.ReactElement
        logOut: React.ReactElement
        map: React.ReactElement
        maximize: React.ReactElement
        menu2: React.ReactElement
        menuArrow: React.ReactElement
        menu: React.ReactElement
        messageCircle: React.ReactElement
        messageSquare: React.ReactElement
        micOff: React.ReactElement
        mic: React.ReactElement
        minimize: React.ReactElement
        minusCircle: React.ReactElement
        minus: React.ReactElement
        minusSquare: React.ReactElement
        monitor: React.ReactElement
        moon: React.ReactElement
        moreHorizontal: React.ReactElement
        moreVertical: React.ReactElement
        move: React.ReactElement
        music: React.ReactElement
        navigation2: React.ReactElement
        navigation: React.ReactElement
        npm: React.ReactElement
        options2: React.ReactElement
        options: React.ReactElement
        pantone: React.ReactElement
        paperPlane: React.ReactElement
        pauseCircle: React.ReactElement
        people: React.ReactElement
        percent: React.ReactElement
        personAdd: React.ReactElement
        personDelete: React.ReactElement
        personDone: React.ReactElement
        person: React.ReactElement
        personRemove: React.ReactElement
        phoneCall: React.ReactElement
        phoneMissed: React.ReactElement
        phoneOff: React.ReactElement
        phone: React.ReactElement
        pieChart: React.ReactElement
        pin: React.ReactElement
        playCircle: React.ReactElement
        plusCircle: React.ReactElement
        plus: React.ReactElement
        plusSquare: React.ReactElement
        power: React.ReactElement
        pricetags: React.ReactElement
        printer: React.ReactElement
        questionMarkCircle: React.ReactElement
        questionMark: React.ReactElement
        radioButtonOff: React.ReactElement
        radioButtonOn: React.ReactElement
        radio: React.ReactElement
        recording: React.ReactElement
        refresh: React.ReactElement
        repeat: React.ReactElement
        rewindLeft: React.ReactElement
        rewindRight: React.ReactElement
        save: React.ReactElement
        scissors: React.ReactElement
        search: React.ReactElement
        settings2: React.ReactElement
        settings: React.ReactElement
        shake: React.ReactElement
        share: React.ReactElement
        shieldOff: React.ReactElement
        shield: React.ReactElement
        shoppingBag: React.ReactElement
        shoppingCart: React.ReactElement
        shuffle2: React.ReactElement
        shuffle: React.ReactElement
        skipBack: React.ReactElement
        skipForward: React.ReactElement
        slash: React.ReactElement
        smartphone: React.ReactElement
        speaker: React.ReactElement
        square: React.ReactElement
        star: React.ReactElement
        stopCircle: React.ReactElement
        sun: React.ReactElement
        swap: React.ReactElement
        sync: React.ReactElement
        text: React.ReactElement
        thermometerMinus: React.ReactElement
        thermometer: React.ReactElement
        thermometerPlus: React.ReactElement
        toggleLeft: React.ReactElement
        toggleRight: React.ReactElement
        trash2: React.ReactElement
        trash: React.ReactElement
        trendingDown: React.ReactElement
        trendingUp: React.ReactElement
        tv: React.ReactElement
        twitter: React.ReactElement
        umbrella: React.ReactElement
        undo: React.ReactElement
        unlock: React.ReactElement
        upload: React.ReactElement
        videoOff: React.ReactElement
        video: React.ReactElement
        volumeDown: React.ReactElement
        volumeMute: React.ReactElement
        volumeOff: React.ReactElement
        volumeUp: React.ReactElement
        wifiOff: React.ReactElement
        wifi: React.ReactElement
    }

    interface Index {
        filled: Filled
        outline: Outline
    }
}

export default IconsetTypes